# Generated by Django 5.1.5 on 2025-01-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_disease_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_hospital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medecins',
            field=models.TextField(blank=True, null=True),
        ),
    ]
